app = "ecommerce-frontend"

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://your-backend-url.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
