app = "ecommerce-backend"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "5000"
  NODE_ENV = "production"
  MONGO_URI = "mongodb+srv://khawlasarhan92_db_user:cnxTPFP7QieSLwT4@cluster0.ysfncug.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET = "abcd124oiy56hgsddc"
  CLOUDINARY_CLOUD_NAME = "dw3oqis6h"
  CLOUDINARY_API_KEY = "928218751675538"
  CLOUDINARY_API_SECRET = "_ojN96433ZCq5Cf9MW1gTPKvKEM"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
